#!/bin/bash
echo "Các biến hệ thống của bạn là"
echo "BASH VERSION : $BASH_VERSION"
echo "COLUMNS: $COLUMNS"
echo "HOME: $HOME"
echo "LINES: $LINES"
echo "LOGNAME $LOGNAME"
echo "OSTYPE: $OSTYPE"
echo "PATH: $PATH"
echo "PS1: $PS1"
echo "PWD: $PWD"
echo "SHELL: $SHELL"
echo "USERNAME: $USERNAME"

exit 0
