#! /bin/bash

echo "$1"

if [ -w $1 ]
then
        echo "File có thể ghi"
else
        echo "File không thể ghi"
fi

if [ -r $1 ]
then
        echo "File có thể đọc"
else
        echo "File không thể đọc"
fi

if [ -x $1 ]
then
        echo "File có thể thực thi"
else
        echo "File không thể thực thi"

exit 0
